/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pw_laundry;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY Compaq
 */
public class Rincian_transaksi extends javax.swing.JInternalFrame {
    Connection kon = new koneksi().buka_koneksi();
    Statement stat;
    ResultSet res;
    DefaultTableModel tbm;
    /**
     * Creates new form Rincian_transaksi
     */
    public Rincian_transaksi() {
        initComponents();
        masuk_table();
        kd_oto();
        relasi();
        relasi_tarif();
        
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_no_rinci = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb_no_trans = new javax.swing.JComboBox();
        txt_jumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_tarif = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cmb_jenis = new javax.swing.JComboBox();
        txt_jenis = new javax.swing.JTextField();

        setClosable(true);
        setTitle("RINCIAN TRANSAKSI");

        jLabel2.setText("ID Rincian");

        txt_no_rinci.setEditable(false);

        jLabel3.setText("No Transaksi");

        cmb_no_trans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmb_no_transMouseEntered(evt);
            }
        });

        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyTyped(evt);
            }
        });

        jLabel4.setText("Jumlah");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_bersih.setText("Bersih");
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        tbl_tarif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_tarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tarifMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_tarif);

        jLabel5.setText("ID Pakaian");

        cmb_jenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmb_jenisMouseEntered(evt);
            }
        });

        txt_jenis.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_no_rinci, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addComponent(cmb_no_trans, 0, 164, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cmb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_jenis))))
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jLabel2)
                            .addGap(191, 191, 191)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_bersih)
                                .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(52, 52, 52)))
                    .addGap(18, 18, 18)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txt_no_rinci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_no_trans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan)
                            .addComponent(btn_ubah)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_bersih)
                        .addComponent(btn_hapus))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_no_transMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_no_transMouseEntered
        /*try {
            ResultSet res;
            stat = kon.createStatement();
            res = stat.executeQuery("SELECT * FROM jenis_laundry WHERE"
                + " id_jenis= '" +cmb_no_beli.getSelectedItem() + "'");
            if(res.next()){
                String box = res.getString("nm_jenis");
                txt_jenis.setText(box);
            }else{

            }
            res.close();
        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_cmb_no_transMouseEntered

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        simpan();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        ubah();
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        bersih();
        kd_oto();
        btn_simpan.setEnabled(true);
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
    }//GEN-LAST:event_btn_bersihActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapus();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbl_tarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tarifMouseClicked

        btn_simpan.setEnabled(false);
        btn_ubah.setEnabled(true);
        btn_hapus.setEnabled(true);

        int i = tbl_tarif.getSelectedRow();
        if(i == -1){
            return;
        }

        String a = (String) tbm.getValueAt(i, 0);
        txt_no_rinci.setText(a);

        String c = (String) tbm.getValueAt(i, 2);
        cmb_no_trans.setSelectedItem(c);

        String d = (String) tbm.getValueAt(i, 3);
        txt_jumlah.setText(d);
    }//GEN-LAST:event_tbl_tarifMouseClicked

    private void cmb_jenisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_jenisMouseEntered
        try {
            ResultSet res;
            stat = kon.createStatement();
            res = stat.executeQuery("SELECT * FROM tarif WHERE"
                + " id_pakaian= '" +cmb_jenis.getSelectedItem() + "'");
            if(res.next()){
                String box = res.getString("nm_pakaian");
                txt_jenis.setText(box);
            }else{

            }
            res.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cmb_jenisMouseEntered

    private void txt_jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyTyped
        angka(evt);
    }//GEN-LAST:event_txt_jumlahKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox cmb_jenis;
    private javax.swing.JComboBox cmb_no_trans;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_tarif;
    private javax.swing.JTextField txt_jenis;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_no_rinci;
    // End of variables declaration//GEN-END:variables

    private void masuk_table(){
        try {
            stat=kon.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            
            tbm = new DefaultTableModel();
            tbm.addColumn("No Rincian");
            tbm.addColumn("No Transaksi");    
            tbm.addColumn("ID Pakaian");
            tbm.addColumn("Jumlah");            
            tbl_tarif.setModel(tbm);
            
            res = stat.executeQuery("SELECT * FROM rincian_transaksi");
            while(res.next()){
                tbm.addRow(new Object[]{
                    res.getString("id_rincian"),
                    res.getString("no_transaksi"),   
                    res.getString("id_pakaian"),
                    res.getString("jumlah"),
                });
                tbl_tarif.setModel(tbm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void ubah(){
        try {
            String sql ="UPDATE rincian_transaksi SET"                    
                    + " id_rincian='"             + cmb_no_trans.getSelectedItem()
                    + "', no_transaksi='"         + cmb_no_trans.getSelectedItem()
                    + "', id_pakaian='"           + cmb_jenis.getSelectedItem()
                    + "' WHERE id_rincian= '"     + txt_no_rinci.getText() + "'";
            stat = kon.createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Tersimpan ^-^");
        masuk_table();
        bersih();
        
        btn_simpan.setEnabled(true);
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void simpan(){
        if(txt_no_rinci.getText().equals("")
                ||txt_jumlah.getText().equals("")
                ||cmb_no_trans.getSelectedItem().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Masih ada field yang kosong x_x|");
        }else
        {
           try {
           String sql = "INSERT INTO rincian_transaksi VALUES('"
                +   txt_no_rinci.getText()             + "','"                
                +   cmb_no_trans.getSelectedItem()     + "','"
                +   cmb_jenis.getSelectedItem()         +"','"                   
                +   txt_jumlah.getText()              +   "')";
        stat = kon.createStatement();
        stat.executeUpdate(sql);
        JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Tersimpan ^-^");
        masuk_table();
        bersih();
        kd_oto();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } 
        }  
    }
    
    private void bersih(){
        txt_jumlah.setText("");
    }
    
    private void hapus(){
        try {
            String sql = "DELETE FROM rincian_transaksi WHERE id_rincian='" + txt_no_rinci.getText() + "'";
            stat = kon.createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Terubah ^-^");
            masuk_table();
            bersih();
            kd_oto();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    
    
    private void kd_oto(){
        try {
            String sql = "SELECT MAX(right(id_rincian,2)) FROM rincian_transaksi";
            
            stat=kon.createStatement();
            res = stat.executeQuery(sql);
            while(res.next()){
                int a = res.getInt(1);
                txt_no_rinci.setText("RT0" + Integer.toString(a+1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void relasi(){
        try {
            stat = kon.createStatement();
            res = stat.executeQuery("SELECT * FROM transaksi");
            while(res.next()){
                cmb_no_trans.addItem(res.getString("no_transaksi"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void relasi_tarif(){
        try {
            stat = kon.createStatement();
            res = stat.executeQuery("SELECT * FROM tarif");
            while(res.next()){
                cmb_jenis.addItem(res.getString("id_pakaian"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    void angka(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(rootPane, "Tidak bisa memasukan Huruf");
        }
    }
}
