/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pw_laundry;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY Compaq
 */
public class stok_barang extends javax.swing.JInternalFrame {
    Connection kon = new koneksi().buka_koneksi();
    Statement stat;
    ResultSet res;
    DefaultTableModel tbm;
    
    Object[][] tb;
    String [] judul={
        "Kode Barang", "No Rincian", "Nama Barang", "Stok", "TGL Update Stok"
    };
    
    /**
     * Creates new form stok_barang
     */
    public stok_barang() {
        initComponents();
        masuk_table();
        kd_oto();
            relasi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        cmb_rinci = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        tgl_update = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_stok = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        cmb_cari = new javax.swing.JComboBox();
        txt_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();

        setClosable(true);
        setTitle("STOK BARANG");

        jLabel2.setText("Kode Barang");

        txt_kode.setEditable(false);

        cmb_rinci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmb_rinciMouseEntered(evt);
            }
        });

        jLabel3.setText("Rincian Pembelian");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_bersih.setText("Bersih");
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Barang");

        tgl_update.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    tgl_update.setFormat(2);

    jLabel5.setText("TGL Update");

    jLabel6.setText("Stok");

    txt_stok.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_stokActionPerformed(evt);
        }
    });
    txt_stok.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txt_stokKeyTyped(evt);
        }
    });

    tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tbl_barangMouseClicked(evt);
        }
    });
    jScrollPane3.setViewportView(tbl_barang);

    cmb_cari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cari Berdasarkan:", "kode barang", "nama barang" }));

    btn_cari.setText("cari");
    btn_cari.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_cariActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                        .addComponent(jSeparator1)))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_stok)
                                .addComponent(txt_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addComponent(txt_kode)
                                .addComponent(cmb_rinci, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tgl_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_cari)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_ubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_simpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel3)
                .addComponent(cmb_rinci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tgl_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
            .addGap(18, 18, 18)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_cari)
                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_simpan)
                    .addComponent(btn_hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_ubah)
                    .addComponent(btn_bersih))
                .addContainerGap(335, Short.MAX_VALUE)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_rinciMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_rinciMouseEntered
        /*try {
            ResultSet res;
            stat = kon.createStatement();
            res = stat.executeQuery("SELECT * FROM jenis_laundry WHERE"
                + " id_jenis= '" +cmb_no_beli.getSelectedItem() + "'");
            if(res.next()){
                String box = res.getString("nm_jenis");
                txt_jenis.setText(box);
            }else{

            }
            res.close();
        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_cmb_rinciMouseEntered

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        simpan();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapus();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        bersih();
        kd_oto();

        btn_simpan.setEnabled(true);
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
    }//GEN-LAST:event_btn_bersihActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        ubah();
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void txt_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stokActionPerformed

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked

        btn_simpan.setEnabled(false);
        btn_ubah.setEnabled(true);
        btn_hapus.setEnabled(true);

        int i = tbl_barang.getSelectedRow();
        if(i == -1){
            return;
        }

        String a = (String) tbm.getValueAt(i, 0);
        txt_kode.setText(a);

        String b = (String) tbm.getValueAt(i, 1);
        cmb_rinci.setSelectedItem(b);

        String c = (String) tbm.getValueAt(i, 2);
        txt_nama.setText(c);

        String d = (String) tbm.getValueAt(i, 3);
        txt_stok.setText(d);
    }//GEN-LAST:event_tbl_barangMouseClicked

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        cari();
    }//GEN-LAST:event_btn_cariActionPerformed

    private void txt_stokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stokKeyTyped
        angka(evt);
    }//GEN-LAST:event_txt_stokKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox cmb_cari;
    private javax.swing.JComboBox cmb_rinci;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_barang;
    private datechooser.beans.DateChooserCombo tgl_update;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_stok;
    // End of variables declaration//GEN-END:variables

     private void masuk_table(){
        try {
            stat=kon.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            
            tbm = new DefaultTableModel();
            tbm.addColumn("Kode Barang");
            tbm.addColumn("Rincian Pembelian");    
            tbm.addColumn("Nama Barang");            
            tbm.addColumn("stok");            
            tbm.addColumn("TGL update stok");
                               
            tbl_barang.setModel(tbm);
            
            res = stat.executeQuery("SELECT * FROM barang");
            while(res.next()){
                tbm.addRow(new Object[]{
                    res.getString("kd_barang"),
                    res.getString("no_rincian"),   
                    res.getString("nm_barang"),
                    res.getString("stok"),
                    res.getString("tgl_update_stock"),
                });
                tbl_barang.setModel(tbm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void ubah(){
        try {
            String sql ="UPDATE barang SET"                    
                    + " no_rincian='"    + cmb_rinci.getSelectedItem()
                    + "', nm_barang='"    + txt_nama.getText()
                    + "', stok='"          + txt_stok.getText()
                    + "', tgl_update_stock='"   + tgl_update.getText()
                    + "' WHERE kd_barang= '"       + txt_kode.getText() + "'";
            stat = kon.createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Tersimpan ^-^");
        masuk_table();
        bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void simpan(){
        if(txt_kode.getText().equals("")
                ||txt_stok.getText().equals("")
                ||cmb_rinci.getSelectedItem().equals("")
                || tgl_update.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Masih ada field yang kosong x_x|");
        }else
        {
           try {
           String sql = "INSERT INTO barang VALUES('"
                +txt_kode.getText()           + "','"                
                +cmb_rinci.getSelectedItem()+ "','"
                + txt_nama.getText()       +   "','"
                + txt_stok.getText()        + "','"
                +tgl_update.getText()       +   "')";
        stat = kon.createStatement();
        stat.executeUpdate(sql);
        JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Tersimpan ^-^");
        masuk_table();
        bersih();
        kd_oto();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } 
        }  
    }
    
    private void bersih(){
        txt_stok.setText("");
        txt_nama.setText("");
        
    }
    
    private void hapus(){
        try {
            String sql = "DELETE FROM barang WHERE kd_barang='" + txt_kode.getText() + "'";
            stat = kon.createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Terubah ^-^");
            masuk_table();
            bersih();
            kd_oto();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void kd_oto(){
        try {
            String sql = "SELECT MAX(right(kd_barang,2)) FROM barang";
            
            stat=kon.createStatement();
            res = stat.executeQuery(sql);
            while(res.next()){
                int a = res.getInt(1);
                txt_kode.setText("B00" + Integer.toString(a+1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void relasi(){
        try {
            stat = kon.createStatement();
            res = stat.executeQuery("SELECT * FROM rincian_pembelian");
            while(res.next()){
                cmb_rinci.addItem(res.getString("no_rincian"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void cari(){
        try {
            String sql;
            
            if(cmb_cari.getSelectedIndex()==0){
                sql = "SELECT * FROM barang";
            } else{
                String cari_ber = null;
                if(cmb_cari.getSelectedItem()=="kode barang"){
                    cari_ber = "kd_barang";
                }else if(cmb_cari.getSelectedItem()=="nama barang"){
                    cari_ber = "nm_barang";
                }
                    
                
                sql = "SELECT * FROM barang WHERE " +
                        cari_ber + " LIKE '" + "%" + txt_cari.getText() + "%" + "'";
                
                }
                stat = kon.createStatement();
                res= stat.executeQuery(sql);
                
                ResultSetMetaData meta = res.getMetaData();
                int col = meta.getColumnCount();
                int baris = 0;
                
                while(res.next()){
                    baris = res.getRow();
                }
            
                tb = new Object[baris][col];
                res.beforeFirst();
                int x =0;
                while(res.next()){
                    tb[x][0]=res.getString("kd_barang");
                    tb[x][1]=res.getString("no_rincian");   
                    tb[x][2]=res.getString("nm_barang");
                   tb[x][3]= res.getString("stok");
                    tb[x][4]=res.getString("tgl_update_stock");
                    x++;
                }
                tbl_barang.setModel(new DefaultTableModel(tb,judul));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }

    }
    void angka(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(rootPane, "Tidak bisa memasukan Huruf");
        }
    }
}
