/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pw_laundry;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY Compaq
 */
public class supplier extends javax.swing.JInternalFrame {
     Connection kon = new koneksi().buka_koneksi();
    Statement stat;
    ResultSet res;
    DefaultTableModel tbm;
    
    Object[][] tb;
    String [] judul={
        "ID Supplier", "Nama Supplier", "Alamat", "NO HP"
    };
    
    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();
        masuk_table();
        kd_oto();
        
        txt_no.setDocument(new textLimit(13));
        
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_kd = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        txt_no = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        cmb_cari = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_supp = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setTitle("DATA SUPPLIER");

        txt_kd.setEditable(false);

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        jLabel4.setText("No HP");

        jLabel3.setText("Alamat");

        jLabel1.setText("Nama Supplier");

        jLabel2.setText("ID Supplier");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_bersih.setText("Bersih");
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });

        btn_cari.setText("cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cari Berdasarkan:", "ID", "nama" }));

        tbl_supp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_supp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_suppMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_supp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txt_nama)
                                    .addComponent(txt_no)
                                    .addComponent(txt_kd, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_bersih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cari)))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(txt_kd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btn_simpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_hapus)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_ubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_bersih)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        simpan();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapus();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        ubah();
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        bersih();
        kd_oto();

        btn_simpan.setEnabled(true);
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
    }//GEN-LAST:event_btn_bersihActionPerformed

    private void tbl_suppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_suppMouseClicked

        btn_simpan.setEnabled(false);
        btn_ubah.setEnabled(true);
        btn_hapus.setEnabled(true);

        int i = tbl_supp.getSelectedRow();
        if(i == -1){
            return;
        }

        String a = (String) tbm.getValueAt(i, 0);
        txt_kd.setText(a);

        String b = (String) tbm.getValueAt(i, 1);
        txt_nama.setText(b);

        String c = (String) tbm.getValueAt(i, 2);
        txt_alamat.setText(c);

        String d = (String) tbm.getValueAt(i, 3);
        txt_no.setText(d);
    }//GEN-LAST:event_tbl_suppMouseClicked

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        cari();
    }//GEN-LAST:event_btn_cariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox cmb_cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_supp;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_kd;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_no;
    // End of variables declaration//GEN-END:variables

    private void masuk_table(){
        try {
            stat=kon.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            
            tbm = new DefaultTableModel();
            tbm.addColumn("ID Supplier");
            tbm.addColumn("Nama Supplier");    
            tbm.addColumn("Alamat");
            tbm.addColumn("No HP");
            tbl_supp.setModel(tbm);
            
            res = stat.executeQuery("SELECT * FROM supplier");
            while(res.next()){
                tbm.addRow(new Object[]{
                    res.getString("id_supplier"),
                    res.getString("nm_supplier"),   
                    res.getString("alamat"),
                    res.getString("telp"),
                });
                tbl_supp.setModel(tbm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void ubah(){
        try {
            String sql ="UPDATE supplier SET"                    
                    + " nm_supplier='"   + txt_nama.getText()
                    + "', alamat='"     + txt_alamat.getText()
                    + "', telp='"        + txt_no.getText()
                    + "' WHERE id_supplier= '"       + txt_kd.getText() + "'";
            stat = kon.createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Tersimpan ^-^");
        masuk_table();
        bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void simpan(){
        if(txt_kd.getText().equals("")
                ||txt_nama.getText().equals("")
                || txt_alamat.getText().equals("")
                || txt_no.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Masih ada field yang kosong x_x|");
        }else
        {
           try {
           String sql = "INSERT INTO supplier VALUES('"
                +txt_kd.getText()           + "','"
                +txt_nama.getText()         + "','"
                +txt_alamat.getText()       + "','"
                + txt_no.getText()          + "')";
        stat = kon.createStatement();
        stat.executeUpdate(sql);
        JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Tersimpan ^-^");
        masuk_table();
        bersih();
        kd_oto();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } 
        }  
    }
    
    private void bersih(){
        txt_alamat.setText("");
        txt_no.setText("");
        txt_nama.setText("");
    }
    
    private void hapus(){
        try {
            String sql = "DELETE FROM supplier WHERE id_supplier='" + txt_kd.getText() + "'";
            stat = kon.createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Terubah ^-^");
            masuk_table();
            bersih();
            kd_oto();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data ada di file yang lain, tidak bisa dihapus");
        }
    }
    
    private void kd_oto(){
        try {
            String sql = "SELECT MAX(right(id_supplier,2)) FROM supplier";
            
            stat=kon.createStatement();
            res = stat.executeQuery(sql);
            while(res.next()){
                int a = res.getInt(1);
                txt_kd.setText("S00" + Integer.toString(a+1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void cari(){
        try {
            String sql;
            
            if(cmb_cari.getSelectedIndex()==0){
                sql = "SELECT * FROM supplier";
            } else{
                String cari_ber = null;
                if(cmb_cari.getSelectedItem()=="ID"){
                    cari_ber = "id_supplier";
                }else if(cmb_cari.getSelectedItem()=="nama"){
                    cari_ber = "nm_supplier";
                }
                    
                
                sql = "SELECT * FROM supplier WHERE " +
                        cari_ber + " LIKE '" + "%" + txt_cari.getText() + "%" + "'";
                
                }
                stat = kon.createStatement();
                res= stat.executeQuery(sql);
                
                ResultSetMetaData meta = res.getMetaData();
                int col = meta.getColumnCount();
                int baris = 0;
                
                while(res.next()){
                    baris = res.getRow();
                }
            
                tb = new Object[baris][col];
                res.beforeFirst();
                int x =0;
                while(res.next()){
                    tb[x][0]=res.getString("id_supplier");
                    tb[x][1]=res.getString("nm_supplier");   
                    tb[x][2]=res.getString("alamat");
                    tb[x][3]= res.getString("telp");
                    x++;
                }
                tbl_supp.setModel(new DefaultTableModel(tb,judul));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }

    }
    
}
