/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pw_laundry;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY Compaq
 */
public class tarif extends javax.swing.JInternalFrame {
    Connection kon = new koneksi().buka_koneksi();
    Statement stat;
    ResultSet res;
    DefaultTableModel tbm;
    /**
     * Creates new form tarif
     */
    public tarif() {
        super("TARIF");
        initComponents();
        
        masuk_table();
        kd_oto();
        relasi();
        
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_tarif = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_jenis = new javax.swing.JComboBox();
        txt_jenis = new javax.swing.JTextField();
        txt_tarif = new javax.swing.JTextField();

        setClosable(true);

        tbl_tarif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_tarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tarifMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_tarif);

        jLabel2.setText("ID Pakaian");

        jLabel1.setText("Nama Pakaian");

        txt_id.setEditable(false);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_bersih.setText("Bersih");
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Pakaian");

        jLabel4.setText("Tarif");

        cmb_jenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmb_jenisMouseEntered(evt);
            }
        });

        txt_jenis.setEditable(false);

        txt_tarif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_tarifKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_jenis, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                    .addComponent(txt_tarif)
                    .addComponent(txt_nama)
                    .addComponent(txt_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_bersih)
                    .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_simpan)
                        .addComponent(btn_ubah)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_bersih)
                        .addComponent(btn_hapus)
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_tarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tarifMouseClicked

        btn_simpan.setEnabled(false);
        btn_ubah.setEnabled(true);
        btn_hapus.setEnabled(true);

        int i = tbl_tarif.getSelectedRow();
        if(i == -1){
            return;
        }

        String a = (String) tbm.getValueAt(i, 0);
        txt_id.setText(a);

        String b = (String) tbm.getValueAt(i, 1);
        txt_nama.setText(b);
        
        String c = (String) tbm.getValueAt(i, 2);
        cmb_jenis.setSelectedItem(c);

        String d = (String) tbm.getValueAt(i, 3);
        txt_tarif.setText(d);
    }//GEN-LAST:event_tbl_tarifMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        simpan();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        ubah();
        
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        bersih();

        kd_oto();
        btn_simpan.setEnabled(true);
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
    }//GEN-LAST:event_btn_bersihActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapus();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void cmb_jenisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_jenisMouseEntered
        try {
            ResultSet res;
            stat = kon.createStatement();
            res = stat.executeQuery("SELECT * FROM jenis_laundry WHERE"
                        + " id_jenis= '" +cmb_jenis.getSelectedItem() + "'");
          if(res.next()){
              String box = res.getString("nm_jenis");
              txt_jenis.setText(box);
          }else{
              
          }
          res.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cmb_jenisMouseEntered

    private void txt_tarifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tarifKeyTyped
        // TODO add your handling code here:
        angka(evt);
    }//GEN-LAST:event_txt_tarifKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox cmb_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_tarif;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_jenis;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tarif;
    // End of variables declaration//GEN-END:variables

    private void masuk_table(){
        try {
            stat=kon.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            
            tbm = new DefaultTableModel();
            tbm.addColumn("ID Pakaian");
            tbm.addColumn("Nama Pakaian");    
            tbm.addColumn("ID Jenis Laundry");
            tbm.addColumn("Tarif");
            tbl_tarif.setModel(tbm);
            
            res = stat.executeQuery("SELECT * FROM tarif");
            while(res.next()){
                tbm.addRow(new Object[]{
                    res.getString("id_pakaian"),
                    res.getString("nm_pakaian"),   
                    res.getString("id_jenis"),
                    res.getString("tarif"),
                });
                tbl_tarif.setModel(tbm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void ubah(){
        try {
            String sql ="UPDATE tarif SET"                    
                    + " nm_pakaian='"    + txt_nama.getText()
                    + "', id_jenis='"    + cmb_jenis.getSelectedItem()
                    + "', tarif='"    + txt_tarif.getText()
                    + "' WHERE id_pakaian= '"       + txt_id.getText() + "'";
            stat = kon.createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Tersimpan ^-^");
        masuk_table();
        bersih();
        
        btn_simpan.setEnabled(true);
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void simpan(){
        if(txt_id.equals("")
                ||txt_nama.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Masih ada field yang kosong x_x|");
        }else
        {
           try {
           String sql = "INSERT INTO tarif VALUES('"
                +txt_id.getText()           + "','"
                +txt_nama.getText()         + "','"
                +cmb_jenis.getSelectedItem()+ "','"
                + txt_tarif.getText()       +   "')";
        stat = kon.createStatement();
        stat.executeUpdate(sql);
        JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Tersimpan ^-^");
        masuk_table();
        bersih();
        kd_oto();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } 
        }  
    }
    
    private void bersih(){
        txt_tarif.setText("");
        txt_nama.setText("");
    }
    
    private void hapus(){
        try {
            String sql = "DELETE FROM tarif WHERE id_pakaian='" + txt_id.getText() + "'";
            stat = kon.createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Anda Berhasil Terubah ^-^");
            masuk_table();
            bersih();
            kd_oto();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void kd_oto(){
        try {
            String sql = "SELECT MAX(right(id_pakaian,2)) FROM tarif";
            
            stat=kon.createStatement();
            res = stat.executeQuery(sql);
            while(res.next()){
                int a = res.getInt(1);
                txt_id.setText("P00" + Integer.toString(a+1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void relasi(){
        try {
            stat = kon.createStatement();
            res = stat.executeQuery("SELECT * FROM jenis_laundry");
            while(res.next()){
                cmb_jenis.addItem(res.getString("id_jenis"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    void angka(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(rootPane, "Tidak bisa memasukan Huruf");
        }
    }
}
